pub mod app;
pub mod cleanup;
pub mod commands;
pub mod db;
pub mod diagnostics;
pub mod duplicates;
pub mod export;
pub mod format;
pub mod insights;
pub mod platform;
pub mod profiles;
pub mod rules;
pub mod scanner;
pub mod snapshot;
pub mod storage;
pub mod tree;
pub mod treemap;
pub mod views;
pub mod watcher;

pub use app::{configure_theme, DiskMapApp};
